library("pcalg")
library("SMPracticals")
data(urine)
urine$r <- as.numeric(urine$r)
urine$gravity <- as.numeric(urine$gravity)
urine$osmo <- as.numeric(urine$osmo)
urine$cond <- as.numeric(urine$cond)
urine$urea <- as.numeric(urine$urea)
urine$calc <- as.numeric(urine$calc)
suffStat <- list(C=cor(urine), n=nrow(urine))
pc.fit <- pc(suffStat, indepTest=gaussCItest, p=ncol(urine), alpha=0.005)
plot(pc.fit,labels=colnames(urine), main="Inferred DAG for urine")